"""
@file report_generator.py
@brief Vulnerability report generation and CVE URL management module

Generates structured JSON vulnerability reports for each scanned machine.
Reports include:
- Machine identification and scan timestamp
- CPE to vulnerability mappings
- CVE identifiers with descriptions
- Direct URLs to CVE.org for detailed information

@author Anton Moulin
@date 2025-12-24
@version 1.0

@details
Report format is JSON for easy parsing and integration with:
- SIEM systems
- Vulnerability management platforms
- Custom analysis tools
- Web dashboards
"""

import json
import os
from datetime import datetime
import logging
from constants import CACHE_DIR

logger = logging.getLogger(__name__)


def generate_cve_url(cve_id):
    """
    Generate a direct link to CVE details on cve.mitre.org.
    
    @param cve_id str CVE identifier (e.g., "CVE-2024-1234")
    
    @return str Full URL to CVE details page
    
    @details
    Format: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-XXXX-XXXXX
    
    These URLs are included in:
    - Terminal output (clickable in modern terminals)
    - JSON reports for reference
    """
    return f"https://cve.mitre.org/cgi-bin/cvename.cgi?name={cve_id}"


def save_machine_report(machine_name, vulnerabilities_data):
    """
    Generate and save JSON vulnerability report for a machine.
    
    Creates a timestamped JSON file containing all vulnerabilities found
    on a machine, organized by CPE with clickable CVE references.
    
    @param machine_name str Name of the machine being reported
    @param vulnerabilities_data dict Vulnerability data structure
                                    Format: {cpe: [{cve_id, description}, ...], ...}
    
    @return str Path to generated report file, or None on failure
    
    @details
    Output file location: cache/machines/{machine_name}/vulnerability_report.json
    
    Report structure:
    @code
    {
        "machine": "srv01",
        "timestamp": "2025-12-24T14:30:45.123456",
        "cpes_with_vulnerabilities": [
            {
                "cpe": "cpe:2.3:a:vendor:product:version:...",
                "vulnerabilities": [
                    {
                        "cve_id": "CVE-2024-1234",
                        "description": "Vulnerability description",
                        "cve_url": "https://cve.mitre.org/..."
                    }
                ]
            }
        ]
    }
    @endcode
    """
    report_dir = os.path.join(CACHE_DIR, "machines", machine_name)
    if not os.path.exists(report_dir):
        os.makedirs(report_dir)
    
    # Build report structure
    report = {
        "machine": machine_name,
        "timestamp": datetime.now().isoformat(),
        "cpes_with_vulnerabilities": []
    }
    
    # Process vulnerabilities by CPE
    for cpe, vulns in vulnerabilities_data.items():
        if vulns:  # Only include CPEs with vulnerabilities
            cpe_entry = {
                "cpe": cpe,
                "vulnerabilities": []
            }
            
            for vuln in vulns:
                cve_entry = {
                    "cve_id": vuln["cve_id"],
                    "description": vuln["description"],
                    "cve_url": generate_cve_url(vuln["cve_id"])
                }
                cpe_entry["vulnerabilities"].append(cve_entry)
            
            report["cpes_with_vulnerabilities"].append(cpe_entry)
    
    # Save report to JSON file
    report_file = f"{report_dir}/vulnerability_report.json"
    try:
        with open(report_file, "w") as f:
            f.write(json.dumps(report, indent=2))
        logger.info(f"Vulnerability report saved for {machine_name}: {report_file}")
        return report_file
    except Exception as e:
        logger.error(f"Error saving vulnerability report for {machine_name}: {e}")
        return None


def get_total_vulnerabilities_from_report(report_dict):
    """
    Count total vulnerabilities in a report structure.
    
    @param report_dict dict Report dictionary (as generated by save_machine_report)
    
    @return int Total number of vulnerabilities across all CPEs
    
    @details
    Useful for statistics and summary generation.
    """
    total = 0
    for cpe_entry in report_dict.get("cpes_with_vulnerabilities", []):
        total += len(cpe_entry.get("vulnerabilities", []))
    return total
